name: "Validate"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  static-code-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
        laravel-version:
          - "^8"
          - "^9"
          - "^10"
        exclude:
          - php-version: "7.4"
            laravel-version: "^9"
          - php-version: "7.4"
            laravel-version: "^10"
          - php-version: "8.0"
            laravel-version: "^10"
    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - run: >
          composer require
          illuminate/contracts:${{ matrix.laravel-version }}
          --no-interaction
          --prefer-dist
          --no-progress
          --update-with-all-dependencies
          ${{ matrix.composer.arg }}

      - run: vendor/bin/phpstan
